import type { Product } from '@/store/slices/products.slice';

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Cà phê đen',
    category: 'Cà phê',
    price: 25000,
    image: '/images/products/ca-phe-den.jpg',
    description: 'Cà phê đen truyền thống',
    stock: 100,
    isAvailable: true,
  },
  {
    id: 'prod-2',
    name: 'Cà phê sữa',
    category: 'Cà phê',
    price: 30000,
    image: '/images/products/ca-phe-sua.jpg',
    description: 'Cà phê sữa đá',
    stock: 100,
    isAvailable: true,
  },
  {
    id: 'prod-3',
    name: 'Bạc xỉu',
    category: 'Cà phê',
    price: 30000,
    image: '/images/products/bac-xiu.jpg',
    description: 'Bạc xỉu truyền thống',
    stock: 100,
    isAvailable: true,
  },
  {
    id: 'prod-4',
    name: 'Cappuccino',
    category: 'Cà phê',
    price: 45000,
    image: '/images/products/cappuccino.jpg',
    description: 'Cappuccino Ý',
    stock: 50,
    isAvailable: true,
  },
  {
    id: 'prod-5',
    name: 'Latte',
    category: 'Cà phê',
    price: 45000,
    image: '/images/products/latte.jpg',
    description: 'Latte ngon',
    stock: 50,
    isAvailable: true,
  },
  {
    id: 'prod-6',
    name: 'Trà sữa trân châu',
    category: 'Trà sữa',
    price: 35000,
    image: '/images/products/tra-sua.jpg',
    description: 'Trà sữa trân châu đường đen',
    stock: 80,
    isAvailable: true,
  },
  {
    id: 'prod-7',
    name: 'Trà đào cam sả',
    category: 'Trà',
    price: 35000,
    image: '/images/products/tra-dao.jpg',
    description: 'Trá đào cam sả mát lạnh',
    stock: 60,
    isAvailable: true,
  },
  {
    id: 'prod-8',
    name: 'Sinh tố bơ',
    category: 'Sinh tố',
    price: 40000,
    image: '/images/products/sinh-to-bo.jpg',
    description: 'Sinh tố bơ béo ngậy',
    stock: 30,
    isAvailable: true,
  },
  {
    id: 'prod-9',
    name: 'Bánh mì',
    category: 'Đồ ăn',
    price: 20000,
    image: '/images/products/banh-mi.jpg',
    description: 'Bánh mì thịt',
    stock: 40,
    isAvailable: true,
  },
  {
    id: 'prod-10',
    name: 'Bánh ngọt',
    category: 'Đồ ăn',
    price: 25000,
    image: '/images/products/banh-ngot.jpg',
    description: 'Bánh ngọt các loại',
    stock: 50,
    isAvailable: true,
  },
];
